---
- hosts: webserver
  vars:
    ansible_ssh_private_key_file: /home/freek/.ssh/freek_key
  tasks:
    - name: Install Apache
      apt:
        name: apache2
        state: present
      become: true

    - name: Upload website files to webserver
      synchronize:
        src: ~/ansible_project/website/
        dest: /var/www/html/
      become: true

- hosts: database
  vars:
    ansible_ssh_private_key_file: /home/freek/.ssh/freek_key
  tasks:
    - name: Install MySQL
      apt:
        name: mysql-server
        state: present
      become: true

